### PR TITLE
Rearrange storybook components

### PR DESCRIPTION
**Pull request by nerdlet**
## Description

Fixes # Add a bit of order

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots

image

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by kilemensi — COMMENTED** [review]
👍🏾 @nerdlet 

1. We shouldn't need `FullComponents` folder. What am I missing?
2. `yarn start` fails:
```
ERROR in ./packages/core/src/FullComponents/Footer/index.js
Module not found: Error: Can't resolve '../../QuickLinks' in '/home/clemence/Work/github/CodeForAfrica/COMMONS-UI/packages/core/src/FullComponents/Footer'
 @ ./packages/core/src/FullComponents/Footer/index.js 60:0-57 60:0-57
 @ ./packages/core/src/index.js
 @ ./stories/components.stories.js
 @ ./stories sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.js)$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined

ERROR in ./packages/core/src/FullComponents/Footer/PrimaryFooter.js
Module not found: Error: Can't resolve '../../QuickLinks' in '/home/clemence/Work/github/CodeForAfrica/COMMONS-UI/packages/core/src/FullComponents/Footer'
 @ ./packages/core/src/FullComponents/Footer/PrimaryFooter.js 13:0-42 60:38-48 67:38-48
 @ ./packages/core/src/FullComponents/Footer/index.js
 @ ./packages/core/src/index.js
 @ ./stories/components.stories.js
 @ ./stories sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.js)$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined

ERROR in ./packages/core/src/index.js
Module not found: Error: Can't resolve './QuickLinks' in '/home/clemence/Work/github/CodeForAfrica/COMMONS-UI/packages/core/src'
 @ ./packages/core/src/index.js 16:0-53 16:0-53
 @ ./stories/components.stories.js
 @ ./stories sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.js)$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
```

**Comment by nerdlet** [comment]
> 👍🏾 @nerdlet
> 
> 1. We shouldn't need `FullComponents` folder. What am I missing?
> 2. `yarn start` fails:
> 
> ```
> ERROR in ./packages/core/src/FullComponents/Footer/index.js
> Module not found: Error: Can't resolve '../../QuickLinks' in '/home/clemence/Work/github/CodeForAfrica/COMMONS-UI/packages/core/src/FullComponents/Footer'
>  @ ./packages/core/src/FullComponents/Footer/index.js 60:0-57 60:0-57
>  @ ./packages/core/src/index.js
>  @ ./stories/components.stories.js
>  @ ./stories sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.js)$
>  @ ./.storybook/generated-stories-entry.js
>  @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
> 
> ERROR in ./packages/core/src/FullComponents/Footer/PrimaryFooter.js
> Module not found: Error: Can't resolve '../../QuickLinks' in '/home/clemence/Work/github/CodeForAfrica/COMMONS-UI/packages/core/src/FullComponents/Footer'
>  @ ./packages/core/src/FullComponents/Footer/PrimaryFooter.js 13:0-42 60:38-48 67:38-48
>  @ ./packages/core/src/FullComponents/Footer/index.js
>  @ ./packages/core/src/index.js
>  @ ./stories/components.stories.js
>  @ ./stories sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.js)$
>  @ ./.storybook/generated-stories-entry.js
>  @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
> 
> ERROR in ./packages/core/src/index.js
> Module not found: Error: Can't resolve './QuickLinks' in '/home/clemence/Work/github/CodeForAfrica/COMMONS-UI/packages/core/src'
>  @ ./packages/core/src/index.js 16:0-53 16:0-53
>  @ ./stories/components.stories.js
>  @ ./stories sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.js)$
>  @ ./.storybook/generated-stories-entry.js
>  @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
> ```

The full component  section is there to  document how to use components collectively

**Comment by kilemensi** [comment]
> The full component section is there to document how to use components collectively

_Documentation_ must not have an impact on how we structure components in `packages/core/src` @nerdlet ... If you want to add a section in the Storybook for that, that’s a different story entirely.

**Comment by nerdlet** [comment]
> > The full component section is there to document how to use components collectively
> 
> _Documentation_ must not have an impact on how we structure components in `packages/core/src` @nerdlet ... If you want to add a section in the Storybook for that, that’s a different story entirely.

@kilemensi Removed it

**Comment by kilemensi** [comment]
🔌  came back but `yarn start` still fails @nerdlet :
```
ERROR in ./packages/core/src/index.js
Module not found: Error: Can't resolve './QuickLinks' in '/home/clemence/Work/github/CodeForAfrica/COMMONS-UI/packages/core/src'
 @ ./packages/core/src/index.js 16:0-53 16:0-53
 @ ./stories/components.stories.js
 @ ./stories sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.js)$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
```

**Review by kilemensi — APPROVED** [review]
👍🏾 @nerdlet 

-----------------

Not sure about the organization e.g. components under Navigation are actually just showcase components but I guess we can discuss / improve this slowly over time.

**Pull request merged**
